def generate_html(domain, classified, scored):
    assets = classified["assets"]
    score = scored["score"]
    overall = scored["overall_risk"]
    breakdown = scored["breakdown"]

    # Count asset types
    type_counts = {}
    for a in assets:
        t = a["classification"]
        type_counts[t] = type_counts.get(t, 0) + 1

    asset_rows = ""
    for a in assets:
        asset_rows += f"""
        <tr>
            <td>{a['hostname']}</td>
            <td>{a['classification']}</td>
            <td style="color:{risk_color(a['risk_level'])};font-weight:bold;">
                {a['risk_level']}
            </td>
            <td>{a.get('confidence','')}</td>
        </tr>
        """

    return f"""
<!DOCTYPE html>
<html>
<head>
<title>Sentinel-X Security Report | {domain}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<style>
body {{
    font-family: Arial, sans-serif;
    background: #f4f6f8;
    margin: 0;
}}
.header {{
    background: #0f172a;
    color: white;
    padding: 25px;
}}
.card {{
    background: white;
    margin: 20px;
    padding: 20px;
    border-radius: 10px;
}}
table {{
    width: 100%;
    border-collapse: collapse;
}}
th, td {{
    padding: 10px;
    border-bottom: 1px solid #ddd;
}}
th {{
    background: #f0f0f0;
}}
canvas {{
    max-width: 600px;
    margin: auto;
}}
.footer {{
    text-align: center;
    padding: 15px;
    color: #555;
}}
</style>
</head>

<body>

<div class="header">
    <h1>🛡️ Sentinel-X Security Report</h1>
    <p><b>Target:</b> {domain}</p>
    <p><b>Date:</b> {time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())}</p>
</div>

<div class="card">
    <h2>📊 Executive Summary</h2>
    <p>
        Overall Risk:
        <b style="color:{risk_color(overall)}">{overall}</b>
        &nbsp; | &nbsp;
        Score: <b>{score}/100</b>
    </p>
    <canvas id="riskScoreChart"></canvas>
</div>

<div class="card">
    <h2>⚠️ Risk Breakdown</h2>
    <canvas id="riskPie"></canvas>
</div>

<div class="card">
    <h2>📈 Asset Type Distribution</h2>
    <canvas id="assetBar"></canvas>
</div>

<div class="card">
    <h2>🌐 Exposed Assets</h2>
    <table>
        <tr>
            <th>Asset</th>
            <th>Type</th>
            <th>Risk</th>
            <th>Confidence</th>
        </tr>
        {asset_rows}
    </table>
</div>

<div class="footer">
    Generated by <b>Sentinel-X</b> | Ethical Attack Surface Management
</div>

<script>
// Risk Score Bar
new Chart(document.getElementById('riskScoreChart'), {{
    type: 'bar',
    data: {{
        labels: ['Risk Score'],
        datasets: [{{
            label: 'Score',
            data: [{score}],
            backgroundColor: '{risk_color(overall)}'
        }}]
    }},
    options: {{
        scales: {{
            y: {{
                beginAtZero: true,
                max: 100
            }}
        }}
    }}
}});

// Risk Breakdown Pie
new Chart(document.getElementById('riskPie'), {{
    type: 'pie',
    data: {{
        labels: ['Critical', 'High', 'Medium', 'Low'],
        datasets: [{{
            data: [
                {breakdown['CRITICAL']},
                {breakdown['HIGH']},
                {breakdown['MEDIUM']},
                {breakdown['LOW']}
            ],
            backgroundColor: ['#ff4d4d', '#ff944d', '#ffd11a', '#5cd65c']
        }}]
    }}
}});

// Asset Type Bar
new Chart(document.getElementById('assetBar'), {{
    type: 'bar',
    data: {{
        labels: {list(type_counts.keys())},
        datasets: [{{
            label: 'Assets',
            data: {list(type_counts.values())},
            backgroundColor: '#4f46e5'
        }}]
    }},
    options: {{
        scales: {{
            y: {{
                beginAtZero: true
            }}
        }}
    }}
}});
</script>

</body>
</html>
"""
